//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFFICE_AUTOMATION_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bank_master()
        {
            this.BILLs = new HashSet<BILL>();
            this.files = new HashSet<file>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string BANK_EMAIL { get; set; }
        public string CC { get; set; }
        public string PARTICULAR { get; set; }
        public string ADDRESS { get; set; }
        public string MOBILE { get; set; }
        public Nullable<int> NO_OF_YEAR { get; set; }
        public string NEC { get; set; }
        public Nullable<int> FEES { get; set; }
        public bool IS_ACTIVE { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
        public System.DateTime ENT_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> BILL_FORMATE_ID { get; set; }
        public Nullable<int> LEGAL_FEES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> files { get; set; }
    }
}
