//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFFICE_AUTOMATION_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class city_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public city_master()
        {
            this.files = new HashSet<file>();
            this.files1 = new HashSet<file>();
            this.files2 = new HashSet<file>();
        }
    
        public int ID { get; set; }
        public string VILLAGE { get; set; }
        public Nullable<int> SUB_DIST_ID { get; set; }
        public Nullable<int> DIST_ID { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> files1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> files2 { get; set; }
    }
    public class Villages
    {
        public int Id { get; set; }
        public string Village { get; set; }
        public string SubDist { get; set; }
        public string Dist { get; set; }
        public int SUB_DIST_ID { get; set; }
        public int DIST_ID { get; set; }
    }
}
