//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFFICE_AUTOMATION_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class communication
    {
        public int ID { get; set; }
        public Nullable<int> F_ID { get; set; }
        public Nullable<int> A_ID { get; set; }
        public Nullable<bool> SMS { get; set; }
        public string SMS_CONTENT { get; set; }
        public string EMAIL_CONTENT { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
        public System.DateTime ENT_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string TO { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string ATTACHMENT { get; set; }
        public string MOBILE_NO { get; set; }
        public string SUBJECT { get; set; }
        public string BODY { get; set; }
    
        public virtual agent_master agent_master { get; set; }
        public virtual file file { get; set; }
    }
}
