//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFFICE_AUTOMATION_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuration
    {
        public int Id { get; set; }
        public string FOLDER_PATH { get; set; }
        public string FROM_EMAIL { get; set; }
        public string EM_PASS { get; set; }
        public string HOST { get; set; }
        public string PORT { get; set; }
        public string SENDER { get; set; }
        public string SMS_AUTH_KEY { get; set; }
        public string SEND_SMS_URI { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
