//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFFICE_AUTOMATION_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee_master()
        {
            this.emp_roll_master = new HashSet<emp_roll_master>();
            this.files = new HashSet<file>();
            this.files1 = new HashSet<file>();
            this.notifications = new HashSet<notification>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string MOBILE1 { get; set; }
        public string MOBILE2 { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string ID_PROOF { get; set; }
        public bool IS_ACTIVE { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
        public System.DateTime ENT_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emp_roll_master> emp_roll_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> files1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification> notifications { get; set; }
    }
}
