//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFFICE_AUTOMATION_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public file()
        {
            this.BILLs = new HashSet<BILL>();
            this.communications = new HashSet<communication>();
            this.notifications = new HashSet<notification>();
            this.public_notice = new HashSet<public_notice>();
            this.queries = new HashSet<query>();
        }
    
        public int ID { get; set; }
        public Nullable<int> R_NO { get; set; }
        public string CUSTOMERNAME { get; set; }
        public string PROPERTY_DETAILS { get; set; }
        public Nullable<int> A_ID { get; set; }
        public Nullable<int> B_ID { get; set; }
        public Nullable<System.DateTime> INWARD_DATE { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public string REMARKS { get; set; }
        public string A_BLOCK_NO { get; set; }
        public string A_REVENUE_SURVEY_NUM { get; set; }
        public string A_PLOT_FLAT_NUM { get; set; }
        public string S_BLOCK_NO { get; set; }
        public string S_REVENUE_SURVEY_NUM { get; set; }
        public string S_PLOT_FLAT_NUM { get; set; }
        public string NEC { get; set; }
        public string CERTIFIED_COPY { get; set; }
        public string APPLICATION_NO { get; set; }
        public Nullable<int> VILLAGE { get; set; }
        public Nullable<int> SUBDIST { get; set; }
        public Nullable<int> DISTRICT { get; set; }
        public Nullable<int> RECEIVER { get; set; }
        public Nullable<int> NO_OF_YEAR { get; set; }
        public Nullable<bool> IS_PN_APPLICABLE { get; set; }
        public Nullable<int> ASSIGN_TO { get; set; }
        public string T { get; set; }
        public Nullable<System.DateTime> T_DATE { get; set; }
        public string S { get; set; }
        public Nullable<System.DateTime> S_DATE { get; set; }
        public string Q { get; set; }
        public Nullable<System.DateTime> Q_DATE { get; set; }
        public string OVLOD { get; set; }
        public Nullable<System.DateTime> OV_DATE { get; set; }
        public string PN { get; set; }
        public Nullable<System.DateTime> PN_DATE { get; set; }
        public string D { get; set; }
        public Nullable<System.DateTime> D_DATE { get; set; }
        public string STATUS_REMARKS { get; set; }
        public Nullable<int> SEARCH_FEES { get; set; }
        public Nullable<bool> IS_PAID { get; set; }
        public string PAID_REMARKS { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
        public Nullable<System.DateTime> ENT_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string FILE_NAME { get; set; }
        public Nullable<int> LEGAL_FEES { get; set; }
    
        public virtual agent_master agent_master { get; set; }
        public virtual bank_master bank_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        public virtual city_master city_master { get; set; }
        public virtual city_master city_master1 { get; set; }
        public virtual city_master city_master2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<communication> communications { get; set; }
        public virtual employee_master employee_master { get; set; }
        public virtual employee_master employee_master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification> notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<public_notice> public_notice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<query> queries { get; set; }
    }
}
