//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFFICE_AUTOMATION_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMATION
    {
        public int ID { get; set; }
        public string OWNER_NAME { get; set; }
        public string STUDY { get; set; }
        public string PROFESSION { get; set; }
        public string ADDRESS { get; set; }
        public string TELEPHONE_NO { get; set; }
        public string MOBILE_NO { get; set; }
        public string PANCARD_NO { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
    }
}
