//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFFICE_AUTOMATION_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BrinalEntitiesdatabase1 : DbContext
    {
        public BrinalEntitiesdatabase1()
            : base("name=BrinalEntitiesdatabase1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agent_master> agent_master { get; set; }
        public virtual DbSet<bank_master> bank_master { get; set; }
        public virtual DbSet<BILL> BILLs { get; set; }
        public virtual DbSet<city_master> city_master { get; set; }
        public virtual DbSet<communication> communications { get; set; }
        public virtual DbSet<configuration> configurations { get; set; }
        public virtual DbSet<emp_roll_master> emp_roll_master { get; set; }
        public virtual DbSet<employee_master> employee_master { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<INFORMATION> INFORMATION { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<propertity_details> propertity_details { get; set; }
        public virtual DbSet<public_notice> public_notice { get; set; }
        public virtual DbSet<query> queries { get; set; }
        public virtual DbSet<TEMPLATE> TEMPLATEs { get; set; }
    }
}
