//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFFICE_AUTOMATION_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notification
    {
        public int ID { get; set; }
        public Nullable<int> FILE_ID { get; set; }
        public string MESSAGE { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
        public Nullable<bool> IS_READ { get; set; }
        public Nullable<System.DateTime> ENT_DATE { get; set; }
    
        public virtual employee_master employee_master { get; set; }
        public virtual file file { get; set; }
    }
}
