//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFFICE_AUTOMATION_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class propertity_details
    {
        public int ID { get; set; }
        public string PROPERTITY_DETAIL { get; set; }
        public string A_BLOCK_NO { get; set; }
        public string A_REVENUE_SURVEY_NUM { get; set; }
        public string A_PLOT_FLAT_NUM { get; set; }
        public string REASON { get; set; }
    }
}
