//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OFFICE_AUTOMATION_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class query
    {
        public int ID { get; set; }
        public int FILE_ID { get; set; }
        public string QUERY_REMARK { get; set; }
        public string OV { get; set; }
        public string LOD { get; set; }
        public string SMS_CONTENT { get; set; }
        public string EMAIL_CONTENT { get; set; }
        public Nullable<bool> IS_RESOLVE { get; set; }
        public Nullable<int> SENT_TO { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
        public Nullable<System.DateTime> ENT_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    
        public virtual agent_master agent_master { get; set; }
        public virtual file file { get; set; }
    }
}
